Update to upstream 2.10.32
snapcrafters/gimp pull request #198
Opened 2022-08-06 11:09 UTC by realHenningLorenzen

2022-08-19 15:51 UTC, diddledani requested changes

2022-08-19 15:51 UTC, diddledani commented on snap/snapcraft.yaml
>      source-checksum: sha256/6fd58a0cdcc7702258adaeffb573a389228ae8f0eff47578efda2309b61b2ca6
You need to add the expected checksum for the new gegl tarball to this line.

2022-08-22 12:40 UTC, realHenningLorenzen commented on snap/snapcraft.yaml
>      source-checksum: sha256/6fd58a0cdcc7702258adaeffb573a389228ae8f0eff47578efda2309b61b2ca6
Done

2022-08-23 02:43 UTC, diddledani approved these changes
Looks good to me! lets see if the build check complains...

2022-08-23 18:24 UTC, diddledani commented
I'm investigating the build failure. I think it is specific to GitHub Actions - running the same build locally is succeeding.

2022-08-23 20:07 UTC, merged

2022-08-23 20:07 UTC, diddledani commented
I'm gonna go ahead and merge this anyway, as I can't get it to fail to build here... hopefully the snapcraft.io build farm will not have any issue either :-)

2022-11-04 14:48 UTC, linghengqian commented
@diddledani Hi, 2.10.32 has been at latest/edge for a long time, can we push this version to latest/stable?  Refer to https://snapcraft.io/gimp .