Set necessary env for system gtk themes to work and clean up content     interfaces
snapcrafters/gimp pull request #97
Opened 2020-01-31 21:09 UTC by kenvandine

This also reverts a previous commit which disabled the usage of gtk2-common-themes.  This was originally done because gtk2-common-themes was only built for amd64.  We'll soon have gtk2-common-themes for all supported architectures.

2020-01-31 21:16 UTC, diddledan commented on snap/snapcraft.yaml
> +  GTK_PATH: $SNAP/lib/gtk-2.0
does this break GTK3?

2020-01-31 21:19 UTC, diddledan commented on snap/snapcraft.yaml
> +  GTK_PATH: $SNAP/lib/gtk-2.0
Yes, it looks like the symlinks created in the `gnome-extension` part should be adjusted so we don't need to set `GTK_PATH` or GTK3 will be inoperable. (Line 170 and 171)

2020-01-31 21:21 UTC, diddledan commented on snap/snapcraft.yaml
> +  GTK_PATH: $SNAP/lib/gtk-2.0
Also see the GTK3 version linking into the platform snap on 167 and 168 for inspiration :-)

2020-01-31 21:23 UTC, lucyllewy requested changes

2020-01-31 21:23 UTC, diddledan commented on patches/desktop-launch.patch
> ++  ln -s "$SNAP"/usr/lib/"$ARCH"/gtk-2.0/2.10.0/immodules/*.so "$GTK_IM_MODULE_DIR"
Should we forcibly make these symlinks to allow for a symlink already existing but pointing elsewhere?
```suggestion
+  ln -sf "$SNAP"/usr/lib/"$ARCH"/gtk-2.0/2.10.0/immodules/*.so "$GTK_IM_MODULE_DIR"
```

2020-01-31 21:23 UTC, diddledan commented on patches/desktop-launch.patch
> ++  ln -s "$SNAP_DESKTOP_RUNTIME"/usr/lib/"$ARCH"/gtk-3.0/3.0.0/immodules/*.so "$GTK3_IM_MODULE_DIR"
See above.
```suggestion
+  ln -sf "$SNAP_DESKTOP_RUNTIME"/usr/lib/"$ARCH"/gtk-3.0/3.0.0/immodules/*.so "$GTK3_IM_MODULE_DIR"
```

2020-01-31 21:52 UTC, kenvandine commented on snap/snapcraft.yaml
> +  GTK_PATH: $SNAP/lib/gtk-2.0
> does this break GTK3?

I don't think GTK3 uses GTK_PATH.

2024-01-19 15:28 UTC, jnsgruk commented
This is no longer relevant as far as I can tell, and already fixed on both the `candidate` and `preview` branches. Thanks all!

2024-01-19 15:28 UTC, closed without merging